In [2]:
pip install xlsxwriter

Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
pip install pandas

Collecting pandas
  Using cached pandas-3.0.1-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.4.3-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tanjunjie\onedrive - srkk group\project\watson_entriesmatching\.venv-1\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\tanjunjie\onedrive - srkk group\project\watson_entriesmatching\.venv-1\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.1-cp314-cp314-win_amd64.whl (9.9 MB)
Downloading numpy-2.4.3-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ------------ --------------------------- 3.9/12.4 MB 46.1 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 63.7 MB/s  0:00:00
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.4.3 pandas-3.0.1 tzdata-2025.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [55]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\tanjunjie\onedrive - srkk group\project\watson_entriesmatching\.venv-1\lib\site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

### Import Libraries and set path

In [58]:
import polars as pl
from pathlib import Path
import fastexcel
import pandas as pd
import xlsxwriter

### Function Definition

In [3]:
def read_excel(path: Path, sheet_pattern: str | None = None, had_header: bool = True) -> pl.DataFrame:
    """
    Read matching sheets from an Excel file into a single Polars DataFrame.
    
    - sheet_pattern: prefix to match sheet names (e.g. "Income" matches "Income - 1", "Income - 2").
                     None = read all sheets.
    - had_header: whether the sheet has a header row.
    """
    reader = fastexcel.read_excel(path)
    print(f"  Sheets in {path.name}: {reader.sheet_names}")

    # Filter sheets by pattern
    sheets = [s for s in reader.sheet_names
              if sheet_pattern is None or s.startswith(sheet_pattern)]
    print(f"  Matching sheets: {sheets}")

    dfs = []
    for name in sheets:
        df = pl.read_excel(path, sheet_name=name, has_header=had_header)
        df = df.with_columns(pl.lit(name).alias("_source_sheet"))
        dfs.append(df)

    if not dfs:
        return pl.DataFrame()

    combined = pl.concat(dfs, how="diagonal_relaxed") if len(dfs) > 1 else dfs[0]
    return combined.with_columns(pl.lit(path.name).alias("_source_file"))

In [4]:
def concat_files(files: list[Path], label: str, sheet_pattern: str | int | None = None, has_header: bool = True) -> pl.DataFrame:
    if not files:
        return pl.DataFrame()
    dfs = []
    for f in files:
        df = read_excel(f, sheet_pattern=sheet_pattern, had_header=has_header)
        if label == "income_all" and not has_header:
            header = df.row(2)
            df = df.slice(3)
            df.columns = header
            dfs.append(df)
        elif label == "balance_all" and not has_header:
            header =df.row(13)
            df = df.slice(14)
            df.columns = header
            dfs.append(df)
        print(f"  Loaded {f.name}: {df.shape}")
    combined = pl.concat(dfs, how="diagonal_relaxed")
    # before = combined.height
    # Drop duplicates (exclude _source_file so rows from overlapping files are caught)
    # data_cols = [c for c in combined.columns if c != "_source_file"]
    # combined = combined.unique(subset=data_cols, keep="first")
    # after = combined.height
    # dupes = before - after
    # print(f"=> {label}: {combined.shape} (removed {dupes} duplicate rows)\n")
    return combined

### Assign File locaiton

In [5]:
root = Path(r"c:\Users\TanJunJie\OneDrive - SRKK Group\Project\watson_entriesmatching\OneDrive_2026-03-09\Shopee Sample Reports (Testing)\scenario1")

# Find all .xlsx files recursively
xlsx_files = sorted(root.rglob("*.xlsx"))

### Bringing Income Report

In [6]:
# --- Load & concatenate by report type ---
income_files = [f for f in xlsx_files if f.name.startswith("Income.released")]
print("=== Income Released ===")
income_all = concat_files(income_files, "income_all", sheet_pattern="Income", has_header=False)

=== Income Released ===
  Sheets in Income.released.my.20251231_20251231.xlsx: ['Summary', 'Service Fee Details', 'Shipping Fee Discrepancy', 'Income - 1', 'Adjustment', 'Income - 2']
  Matching sheets: ['Income - 1', 'Income - 2']
  Loaded Income.released.my.20251231_20251231.xlsx: (15021, 49)
  Sheets in Income.released.my.20260101_20260101.xlsx: ['Summary', 'Service Fee Details', 'Shipping Fee Discrepancy', 'Adjustment', 'Income - 1', 'Income - 2']
  Matching sheets: ['Income - 1', 'Income - 2']
  Loaded Income.released.my.20260101_20260101.xlsx: (12599, 49)
  Sheets in Income.released.my.20260102_20260102.xlsx: ['Summary', 'Service Fee Details', 'Shipping Fee Discrepancy', 'Adjustment', 'Income - 1', 'Income - 2']
  Matching sheets: ['Income - 1', 'Income - 2']
  Loaded Income.released.my.20260102_20260102.xlsx: (16012, 49)
  Sheets in Income.released.my.20260103_20260103.xlsx: ['Summary', 'Service Fee Details', 'Shipping Fee Discrepancy', 'Adjustment', 'Income - 1', 'Income - 2']
  Matching sheets: ['Income - 1', 'Income - 2']
  Loaded Income.released.my.20260103_20260103.xlsx: (16068, 49)
  Sheets in Income.released.my.20260104_20260104.xlsx: ['Summary', 'Service Fee Details', 'Shipping Fee Discrepancy', 'Adjustment', 'Income - 1', 'Income - 2']
  Matching sheets: ['Income - 1', 'Income - 2']
  Loaded Income.released.my.20260104_20260104.xlsx: (15339, 49)
  Sheets in Income.released.my.20260105_20260105.xlsx: ['Summary', 'Service Fee Details', 'Shipping Fee Discrepancy', 'Adjustment', 'Income - 1', 'Income - 2']
  Matching sheets: ['Income - 1', 'Income - 2']
  Loaded Income.released.my.20260105_20260105.xlsx: (16444, 49)
  Sheets in Income.released.my.20260106_20260106.xlsx: ['Summary', 'Service Fee Details', 'Shipping Fee Discrepancy', 'Adjustment', 'Income - 1', 'Income - 2']
  Matching sheets: ['Income - 1', 'Income - 2']
  Loaded Income.released.my.20260106_20260106.xlsx: (15445, 49)
  Sheets in Income.released.my.20260107_20260107.xlsx: ['Summary', 'Service Fee Details', 'Shipping Fee Discrepancy', 'Adjustment', 'Income - 1', 'Income - 2']
  Matching sheets: ['Income - 1', 'Income - 2']
  Loaded Income.released.my.20260107_20260107.xlsx: (15849, 49)

In [7]:
# Filter to only "Order" view (exclude "Settlement" which has overlapping data but different granul
income_all.head()

shape: (5, 56)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Sequence   ┆ View By ┆ Order ID  ┆ Shop Name ┆ … ┆ Income.re ┆ Income.re ┆ Income.re ┆ Income.re │
│ No.        ┆ ---     ┆ ---       ┆ ---       ┆   ┆ leased.my ┆ leased.my ┆ leased.my ┆ leased.my │
│ ---        ┆ str     ┆ str       ┆ str       ┆   ┆ .20260104 ┆ .20260105 ┆ .20260106 ┆ .20260107 │
│ str        ┆         ┆           ┆           ┆   ┆ _20…      ┆ _20…      ┆ _20…      ┆ _20…      │
│            ┆         ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆         ┆           ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1          ┆ Order   ┆ 251230QHF ┆ Watsons   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆         ┆ 7YGBE     ┆ Malaysia  ┆   ┆           ┆           ┆           ┆           │
│ 2          ┆ Sku     ┆ 251230QHF ┆ Watsons   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆         ┆ 7YGBE     ┆ Malaysia  ┆   ┆           ┆           ┆           ┆           │
│ 3          ┆ Order   ┆ 251230PMP ┆ Watsons   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆         ┆ 6MTW6     ┆ Malaysia  ┆   ┆           ┆           ┆           ┆           │
│ 4          ┆ Sku     ┆ 251230PMP ┆ Watsons   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆         ┆ 6MTW6     ┆ Malaysia  ┆   ┆           ┆           ┆           ┆           │
│ 5          ┆ Order   ┆ 251230PB5 ┆ Watsons   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆         ┆ YG8HT     ┆ Malaysia  ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
income_all.columns

['Sequence No.',
 'View By',
 'Order ID',
 'Shop Name',
 'refund id',
 'Product ID',
 'Product Name',
 'Order Creation Date',
 'Payout Completed Date',
 'Release Channel',
 'Order Type',
 'Hot Listing',
 'Total Released Amount (RM)',
 'Product Price',
 'Refund Amount',
 'Shipping Fee Paid by Buyer (excl. SST)',
 'Shipping Fee Charged by Logistic Provider',
 'Seller Paid Shipping Fee SST',
 'Shipping Rebate From Shopee',
 'Reverse Shipping Fee',
 'Reverse Shipping Fee SST',
 'Saver Programme Shipping Fee Savings',
 'Return to Seller Fee',
 'Rebate Provided by Shopee',
 'Voucher Sponsored by Seller',
 'Coin Cashback Sponsored by Seller',
 'Commission Fee (incl. SST)',
 'Service Fee (Incl. SST)',
 'Transaction Fee (Incl. SST)',
 'AMS Commission Fee',
 'Saver Programme Fee (Incl. SST)',
 'Username (Buyer)',
 'Amount Paid By Buyer',
 'Transaction Fee Rate (%)',
 'Buyer Payment Method',
 'Buyer Payment Method Details_1(if applicable)',
 'Payment Details / Installment Plan',
 'Shipping Fee Promotion by Seller',
 'Shipping provider',
 'Courier Name',
 'Voucher Code From Seller',
 'Lost Compensation',
 'Cash refund to buyer amount',
 'Pro-rated coin offset for return refund Items',
 'Pro-rated Shopee voucher offset for returned items',
 'Pro-rated Bank Payment Channel Promotion  for return refund Items',
 'Pro-rated Shopee Payment Channel Promotion  for return refund Items',
 'Income - 1',
 'Income.released.my.20251231_20251231.xlsx',
 'Income.released.my.20260101_20260101.xlsx',
 'Income.released.my.20260102_20260102.xlsx',
 'Income.released.my.20260103_20260103.xlsx',
 'Income.released.my.20260104_20260104.xlsx',
 'Income.released.my.20260105_20260105.xlsx',
 'Income.released.my.20260106_20260106.xlsx',
 'Income.released.my.20260107_20260107.xlsx']

In [27]:
#Select only relevant columns for matching (exclude "View By" which is used for filtering but not needed in matching)
income_all_normalized = (
    income_all.
    filter(pl.col("View By")== "Order")
    .select(
    ['Sequence No.',
    'Order ID',
    'Order Creation Date',
    'Payout Completed Date',

    'Total Released Amount (RM)',
    'Product Price',
    'Refund Amount',
    'Shipping Fee Paid by Buyer (excl. SST)',
    'Shipping Fee Charged by Logistic Provider',
    'Seller Paid Shipping Fee SST',
    'Shipping Rebate From Shopee',
    'Reverse Shipping Fee',
    'Reverse Shipping Fee SST',
    'Saver Programme Shipping Fee Savings',
    'Return to Seller Fee',
    'Rebate Provided by Shopee',
    'Voucher Sponsored by Seller',
    'Coin Cashback Sponsored by Seller',
    'Commission Fee (incl. SST)',
    'Service Fee (Incl. SST)',
    'Transaction Fee (Incl. SST)',
    'AMS Commission Fee',
    'Saver Programme Fee (Incl. SST)',

    'Username (Buyer)',
    'Transaction Fee Rate (%)',
    'Buyer Payment Method',
    'Buyer Payment Method Details_1(if applicable)',
    'Payment Details / Installment Plan',

    'Voucher Code From Seller',
    'Lost Compensation',
    ])
    .with_columns([
        pl.col('Order ID').cast(pl.Utf8).str.strip_chars(),
        pl.col('Total Released Amount (RM)').cast(pl.Float64, strict=False),
        pl.col('Order Creation Date').cast(pl.Utf8).str.strptime(pl.Date, '%Y-%m-%d', strict=False),
        pl.col('Payout Completed Date').cast(pl.Utf8).str.strptime(pl.Date, '%Y-%m-%d', strict=False),
        pl.col('Product Price').cast(pl.Float64, strict=False),
        pl.col('Refund Amount').cast(pl.Float64, strict=False),
        pl.col('Shipping Fee Paid by Buyer (excl. SST)').cast(pl.Float64, strict=False),
        pl.col('Shipping Fee Charged by Logistic Provider').cast(pl.Float64, strict=False),
        pl.col('Seller Paid Shipping Fee SST').cast(pl.Float64, strict=False),
        pl.col('Shipping Rebate From Shopee').cast(pl.Float64, strict=False),
        pl.col('Reverse Shipping Fee').cast(pl.Float64, strict=False),
        pl.col('Reverse Shipping Fee SST').cast(pl.Float64, strict=False),
        pl.col('Saver Programme Shipping Fee Savings').cast(pl.Float64, strict=False),
        pl.col('Return to Seller Fee').cast(pl.Float64, strict=False),
        pl.col('Rebate Provided by Shopee').cast(pl.Float64, strict=False),
        pl.col('Voucher Sponsored by Seller').cast(pl.Float64, strict=False),
        pl.col('Coin Cashback Sponsored by Seller').cast(pl.Float64, strict=False),
        pl.col('Commission Fee (incl. SST)').cast(pl.Float64, strict=False),
        pl.col('Service Fee (Incl. SST)').cast(pl.Float64, strict=False),
        pl.col('Transaction Fee (Incl. SST)').cast(pl.Float64, strict=False),
        pl.col('AMS Commission Fee').cast(pl.Float64, strict=False),
        pl.col('Saver Programme Fee (Incl. SST)').cast(pl.Float64, strict=False),
        pl.col('Transaction Fee Rate (%)').cast(pl.Float64, strict=False),
        pl.col('Lost Compensation').cast(pl.Float64, strict=False),
    ])
    .drop_nulls(['Order ID'])
    )
income_all_normalized.head()

shape: (5, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Sequence  ┆ Order ID  ┆ Order     ┆ Payout    ┆ … ┆ Buyer     ┆ Payment   ┆ Voucher   ┆ Lost Com │
│ No.       ┆ ---       ┆ Creation  ┆ Completed ┆   ┆ Payment   ┆ Details / ┆ Code From ┆ pensatio │
│ ---       ┆ str       ┆ Date      ┆ Date      ┆   ┆ Method    ┆ Installme ┆ Seller    ┆ n        │
│ str       ┆           ┆ ---       ┆ ---       ┆   ┆ Details_1 ┆ nt …      ┆ ---       ┆ ---      │
│           ┆           ┆ date      ┆ date      ┆   ┆ …         ┆ ---       ┆ str       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ str       ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 251230QHF ┆ 2025-12-3 ┆ 2025-12-3 ┆ … ┆           ┆           ┆           ┆ 0.0      │
│           ┆ 7YGBE     ┆ 0         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 251230PMP ┆ 2025-12-3 ┆ 2025-12-3 ┆ … ┆           ┆           ┆           ┆ 0.0      │
│           ┆ 6MTW6     ┆ 0         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 251230PB5 ┆ 2025-12-3 ┆ 2025-12-3 ┆ … ┆           ┆ 12x       ┆           ┆ 0.0      │
│           ┆ YG8HT     ┆ 0         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 7         ┆ 251230PB3 ┆ 2025-12-3 ┆ 2025-12-3 ┆ … ┆           ┆ 3x        ┆           ┆ 0.0      │
│           ┆ GD63E     ┆ 0         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 10        ┆ 251230PAY ┆ 2025-12-3 ┆ 2025-12-3 ┆ … ┆           ┆           ┆           ┆ 0.0      │
│           ┆ 9XQWY     ┆ 0         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Bringing Balance Transaction Report

In [10]:
balance_files = [f for f in xlsx_files if f.name.startswith("my_balance_transaction")]
print("=== Balance Transaction ===")
balance_all = concat_files(balance_files, "balance_all", sheet_pattern="Transaction", has_header=False)

=== Balance Transaction ===
  Sheets in my_balance_transaction_report.shopee.20251231_20260107part_1_of_9.xlsx: ['Transaction Report']
  Matching sheets: ['Transaction Report']
  Loaded my_balance_transaction_report.shopee.20251231_20260107part_1_of_9.xlsx: (5000, 10)
  Sheets in my_balance_transaction_report.shopee.20251231_20260107part_2_of_9.xlsx: ['Transaction Report']
  Matching sheets: ['Transaction Report']
  Loaded my_balance_transaction_report.shopee.20251231_20260107part_2_of_9.xlsx: (5000, 10)
  Sheets in my_balance_transaction_report.shopee.20251231_20260107part_3_of_9.xlsx: ['Transaction Report']
  Matching sheets: ['Transaction Report']
  Loaded my_balance_transaction_report.shopee.20251231_20260107part_3_of_9.xlsx: (5000, 10)
  Sheets in my_balance_transaction_report.shopee.20251231_20260107part_4_of_9.xlsx: ['Transaction Report']
  Matching sheets: ['Transaction Report']
  Loaded my_balance_transaction_report.shopee.20251231_20260107part_4_of_9.xlsx: (5000, 10)
  Sheets in my_balance_transaction_report.shopee.20251231_20260107part_5_of_9.xlsx: ['Transaction Report']
  Matching sheets: ['Transaction Report']
  Loaded my_balance_transaction_report.shopee.20251231_20260107part_5_of_9.xlsx: (5000, 10)
  Sheets in my_balance_transaction_report.shopee.20251231_20260107part_6_of_9.xlsx: ['Transaction Report']
  Matching sheets: ['Transaction Report']
  Loaded my_balance_transaction_report.shopee.20251231_20260107part_6_of_9.xlsx: (5000, 10)
  Sheets in my_balance_transaction_report.shopee.20251231_20260107part_7_of_9.xlsx: ['Transaction Report']
  Matching sheets: ['Transaction Report']
  Loaded my_balance_transaction_report.shopee.20251231_20260107part_7_of_9.xlsx: (5000, 10)
  Sheets in my_balance_transaction_report.shopee.20251231_20260107part_8_of_9.xlsx: ['Transaction Report']
  Matching sheets: ['Transaction Report']
  Loaded my_balance_transaction_report.shopee.20251231_20260107part_8_of_9.xlsx: (5000, 10)
  Sheets in my_balance_transaction_report.shopee.20251231_20260107part_9_of_9.xlsx: ['Transaction Report']
  Matching sheets: ['Transaction Report']
  Loaded my_balance_transaction_report.shopee.20251231_20260107part_9_of_9.xlsx: (1904, 10)

In [11]:
balance_all.columns

['Date',
 'Transaction Type',
 'Description',
 'Order ID',
 'Money Direction',
 'Amount',
 'Status',
 'Balance After Transactions',
 'Transaction Report',
 'my_balance_transaction_report.shopee.20251231_20260107part_1_of_9.xlsx',
 'my_balance_transaction_report.shopee.20251231_20260107part_2_of_9.xlsx',
 'my_balance_transaction_report.shopee.20251231_20260107part_3_of_9.xlsx',
 'my_balance_transaction_report.shopee.20251231_20260107part_4_of_9.xlsx',
 'my_balance_transaction_report.shopee.20251231_20260107part_5_of_9.xlsx',
 'my_balance_transaction_report.shopee.20251231_20260107part_6_of_9.xlsx',
 'my_balance_transaction_report.shopee.20251231_20260107part_7_of_9.xlsx',
 'my_balance_transaction_report.shopee.20251231_20260107part_8_of_9.xlsx',
 'my_balance_transaction_report.shopee.20251231_20260107part_9_of_9.xlsx']

In [12]:

balance_all_normalized = (
    balance_all.
        select(['Date',
        'Transaction Type',
        'Description',
        'Order ID'])
        .with_columns([
        pl.col('Order ID').cast(pl.Utf8).str.strip_chars(),
        pl.col("Date").str.strptime(pl.Datetime, "%Y-%m-%d %H:%M:%S")
    ])
        
)
balance_all_normalized.head(10)

shape: (10, 4)
┌─────────────────────┬──────────────────┬─────────────────────────────────┬────────────────┐
│ Date                ┆ Transaction Type ┆ Description                     ┆ Order ID       │
│ ---                 ┆ ---              ┆ ---                             ┆ ---            │
│ datetime[μs]        ┆ str              ┆ str                             ┆ str            │
╞═════════════════════╪══════════════════╪═════════════════════════════════╪════════════════╡
│ 2026-01-07 23:59:53 ┆ Order Income     ┆ Income from Order #251227FMQA3… ┆ 251227FMQA3XGP │
│ 2026-01-07 23:59:46 ┆ Order Income     ┆ Income from Order #260102VN9VM… ┆ 260102VN9VMVPV │
│ 2026-01-07 23:59:32 ┆ Order Income     ┆ Income from Order #2601045P6TK… ┆ 2601045P6TK6PG │
│ 2026-01-07 23:59:28 ┆ Order Income     ┆ Income from Order #2601045Y4YT… ┆ 2601045Y4YTEG6 │
│ 2026-01-07 23:59:26 ┆ Order Income     ┆ Income from Order #2601045E6UG… ┆ 2601045E6UGTNU │
│ 2026-01-07 23:59:06 ┆ Order Income     ┆ Income from Order #26010575HF5… ┆ 26010575HF5Q6D │
│ 2026-01-07 23:59:02 ┆ Order Income     ┆ Income from Order #26010347C47… ┆ 26010347C470NX │
│ 2026-01-07 23:58:33 ┆ Order Income     ┆ Income from Order #260101UAHS8… ┆ 260101UAHS8FRR │
│ 2026-01-07 23:58:22 ┆ Order Income     ┆ Income from Order #2601069VSE7… ┆ 2601069VSE7UX0 │
│ 2026-01-07 23:58:05 ┆ Order Income     ┆ Income from Order #2512235NA29… ┆ 2512235NA29GPW │
└─────────────────────┴──────────────────┴─────────────────────────────────┴────────────────┘

In [85]:
balance_all.select(pl.col("Status").unique())

shape: (1, 1)
┌───────────────────────┐
│ Status                │
│ ---                   │
│ str                   │
╞═══════════════════════╡
│ Transaction Completed │
└───────────────────────┘

In [88]:
balance_all.filter(pl.col("Order ID")== "251227F28P4MVX")

shape: (0, 18)
┌──────┬────────────┬────────────┬──────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ Date ┆ Transactio ┆ Descriptio ┆ Order ID ┆ … ┆ my_balance ┆ my_balance ┆ my_balance ┆ my_balanc │
│ ---  ┆ n Type     ┆ n          ┆ ---      ┆   ┆ _transacti ┆ _transacti ┆ _transacti ┆ e_transac │
│ str  ┆ ---        ┆ ---        ┆ str      ┆   ┆ on_report. ┆ on_report. ┆ on_report. ┆ tion_repo │
│      ┆ str        ┆ str        ┆          ┆   ┆ …          ┆ …          ┆ …          ┆ rt.…      │
│      ┆            ┆            ┆          ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│      ┆            ┆            ┆          ┆   ┆ str        ┆ str        ┆ str        ┆ str       │
╞══════╪════════════╪════════════╪══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
└──────┴────────────┴────────────┴──────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [14]:
balance_all_withdrawal = balance_all_normalized.filter(pl.col("Transaction Type").is_in(["Withdrawals"]))

In [89]:
path = "../Shopee Payment Master List 180126.xlsx"
recon = pl.read_excel(path,sheet_name="Recon", has_header=True)
recon.head()

Could not determine dtype for column 19, falling back to string
Could not determine dtype for column 20, falling back to string
Could not determine dtype for column 22, falling back to string
Could not determine dtype for column 25, falling back to string
Could not determine dtype for column 26, falling back to string
Could not determine dtype for column 27, falling back to string
Could not determine dtype for column 28, falling back to string
Could not determine dtype for column 29, falling back to string
Could not determine dtype for column 30, falling back to string
Could not determine dtype for column 31, falling back to string
Could not determine dtype for column 32, falling back to string
Could not determine dtype for column 33, falling back to string
Could not determine dtype for column 34, falling back to string
Could not determine dtype for column 35, falling back to string
Could not determine dtype for column 36, falling back to string
Could not determine dtype for column 38, falling back to string
Could not determine dtype for column 39, falling back to string
Could not determine dtype for column 40, falling back to string
Could not determine dtype for column 41, falling back to string
Could not determine dtype for column 42, falling back to string
Could not determine dtype for column 43, falling back to string

shape: (5, 39)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬──────┐
│ OrderNum   ┆ MarketPlac ┆ WorkDate   ┆ SalesCente ┆ … ┆ Shipping  ┆ Shipping  ┆ Oustandin ┆ .    │
│ ---        ┆ eOrderNum  ┆ ---        ┆ rAmount    ┆   ┆ Fee Adj   ┆ Fee Adj 2 ┆ g Balance ┆ ---  │
│ str        ┆ ---        ┆ str        ┆ ---        ┆   ┆ Mth 2     ┆ ---       ┆ ---       ┆ str  │
│            ┆ str        ┆            ┆ f64        ┆   ┆ ---       ┆ str       ┆ f64       ┆      │
│            ┆            ┆            ┆            ┆   ┆ str       ┆           ┆           ┆      │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪══════╡
│ 9523929588 ┆ 250705B8MM ┆ 2025-07-06 ┆ 37.18      ┆ … ┆ null      ┆ null      ┆ 9.25      ┆ null │
│            ┆ 4UH4       ┆            ┆            ┆   ┆           ┆           ┆           ┆      │
│ 9523802829 ┆ 250612C1TJ ┆ 2025-07-07 ┆ -3.0       ┆ … ┆ null      ┆ null      ┆ -3.0      ┆ null │
│            ┆ 9SHE       ┆            ┆            ┆   ┆           ┆           ┆           ┆      │
│ 9523757815 ┆ 250604N6AD ┆ 2025-07-07 ┆ -9.73      ┆ … ┆ null      ┆ null      ┆ -9.73     ┆ null │
│            ┆ 379X       ┆            ┆            ┆   ┆           ┆           ┆           ┆      │
│ 9523971310 ┆ 250711TY92 ┆ 2025-07-13 ┆ 153.78     ┆ … ┆ null      ┆ null      ┆ 2.89      ┆ null │
│            ┆ VWPU       ┆            ┆            ┆   ┆           ┆           ┆           ┆      │
│ 9523975421 ┆ 2507120F7G ┆ 2025-07-14 ┆ 278.03     ┆ … ┆ null      ┆ null      ┆ 0.95      ┆ null │
│            ┆ FHVV       ┆            ┆            ┆   ┆           ┆           ┆           ┆      │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴──────┘

In [91]:
recon = recon.with_columns(pl.col("MarketPlaceOrderNum").cast(pl.Utf8).str.strip_chars().alias("Order ID"))
recon.head()

shape: (5, 40)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬──────┬───────────┐
│ OrderNum   ┆ MarketPlac ┆ WorkDate   ┆ SalesCente ┆ … ┆ Shipping  ┆ Oustandin ┆ .    ┆ Order ID  │
│ ---        ┆ eOrderNum  ┆ ---        ┆ rAmount    ┆   ┆ Fee Adj 2 ┆ g Balance ┆ ---  ┆ ---       │
│ str        ┆ ---        ┆ str        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ str  ┆ str       │
│            ┆ str        ┆            ┆ f64        ┆   ┆ str       ┆ f64       ┆      ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════╪═══════════╡
│ 9523929588 ┆ 250705B8MM ┆ 2025-07-06 ┆ 37.18      ┆ … ┆ null      ┆ 9.25      ┆ null ┆ 250705B8M │
│            ┆ 4UH4       ┆            ┆            ┆   ┆           ┆           ┆      ┆ M4UH4     │
│ 9523802829 ┆ 250612C1TJ ┆ 2025-07-07 ┆ -3.0       ┆ … ┆ null      ┆ -3.0      ┆ null ┆ 250612C1T │
│            ┆ 9SHE       ┆            ┆            ┆   ┆           ┆           ┆      ┆ J9SHE     │
│ 9523757815 ┆ 250604N6AD ┆ 2025-07-07 ┆ -9.73      ┆ … ┆ null      ┆ -9.73     ┆ null ┆ 250604N6A │
│            ┆ 379X       ┆            ┆            ┆   ┆           ┆           ┆      ┆ D379X     │
│ 9523971310 ┆ 250711TY92 ┆ 2025-07-13 ┆ 153.78     ┆ … ┆ null      ┆ 2.89      ┆ null ┆ 250711TY9 │
│            ┆ VWPU       ┆            ┆            ┆   ┆           ┆           ┆      ┆ 2VWPU     │
│ 9523975421 ┆ 2507120F7G ┆ 2025-07-14 ┆ 278.03     ┆ … ┆ null      ┆ 0.95      ┆ null ┆ 2507120F7 │
│            ┆ FHVV       ┆            ┆            ┆   ┆           ┆           ┆      ┆ GFHVV     │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴──────┴───────────┘

In [104]:
recon.filter(pl.col("Order ID") == "2601045R7NTP28")

shape: (1, 40)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬──────┬───────────┐
│ OrderNum   ┆ MarketPlac ┆ WorkDate   ┆ SalesCente ┆ … ┆ Shipping  ┆ Oustandin ┆ .    ┆ Order ID  │
│ ---        ┆ eOrderNum  ┆ ---        ┆ rAmount    ┆   ┆ Fee Adj 2 ┆ g Balance ┆ ---  ┆ ---       │
│ str        ┆ ---        ┆ str        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ str  ┆ str       │
│            ┆ str        ┆            ┆ f64        ┆   ┆ str       ┆ f64       ┆      ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════╪═══════════╡
│ 9524951072 ┆ 2601045R7N ┆ 2026-01-05 ┆ 107.65     ┆ … ┆ null      ┆ 1.0658e-1 ┆ null ┆ 2601045R7 │
│            ┆ TP28       ┆ 00:00:00   ┆            ┆   ┆           ┆ 4         ┆      ┆ NTP28     │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴──────┴───────────┘

In [105]:
recon.filter(pl.col("Order ID") == "260101UF58WU38")

shape: (1, 40)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬──────┬───────────┐
│ OrderNum   ┆ MarketPlac ┆ WorkDate   ┆ SalesCente ┆ … ┆ Shipping  ┆ Oustandin ┆ .    ┆ Order ID  │
│ ---        ┆ eOrderNum  ┆ ---        ┆ rAmount    ┆   ┆ Fee Adj 2 ┆ g Balance ┆ ---  ┆ ---       │
│ str        ┆ ---        ┆ str        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ str  ┆ str       │
│            ┆ str        ┆            ┆ f64        ┆   ┆ str       ┆ f64       ┆      ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════╪═══════════╡
│ 9524930857 ┆ 260101UF58 ┆ 2026-01-05 ┆ 2.73       ┆ … ┆ null      ┆ -8.3267e- ┆ null ┆ 260101UF5 │
│            ┆ WU38       ┆ 00:00:00   ┆            ┆   ┆           ┆ 17        ┆      ┆ 8WU38     │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴──────┴───────────┘

In [116]:
recon.filter(
	(pl.col("Actual Shipping Fee") == 1.06) &
	(pl.col("Pymt Date") == pl.date(2026, 1, 14))
)

shape: (2, 40)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬──────┬───────────┐
│ OrderNum   ┆ MarketPlac ┆ WorkDate   ┆ SalesCente ┆ … ┆ Shipping  ┆ Oustandin ┆ .    ┆ Order ID  │
│ ---        ┆ eOrderNum  ┆ ---        ┆ rAmount    ┆   ┆ Fee Adj 2 ┆ g Balance ┆ ---  ┆ ---       │
│ str        ┆ ---        ┆ str        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ str  ┆ str       │
│            ┆ str        ┆            ┆ f64        ┆   ┆ str       ┆ f64       ┆      ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════╪═══════════╡
│ 9524982329 ┆ 260110P1CN ┆ 2026-01-12 ┆ 141.96     ┆ … ┆ null      ┆ 5.7732e-1 ┆ null ┆ 260110P1C │
│            ┆ KDKW       ┆ 00:00:00   ┆            ┆   ┆           ┆ 5         ┆      ┆ NKDKW     │
│ 9524982329 ┆ 260110P1CN ┆ 2026-01-12 ┆ 141.96     ┆ … ┆ null      ┆ 5.7732e-1 ┆ null ┆ 260110P1C │
│            ┆ KDKW       ┆ 00:00:00   ┆            ┆   ┆           ┆ 5         ┆      ┆ NKDKW     │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴──────┴───────────┘

In [117]:
income_all_normalized.filter(pl.col("Order ID") == "260110P1CNKDKW").head()

shape: (0, 32)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Sequence  ┆ Order ID ┆ Order     ┆ Payout    ┆ … ┆ Voucher   ┆ Lost Comp ┆ Net       ┆ Net       │
│ No.       ┆ ---      ┆ Creation  ┆ Completed ┆   ┆ Code From ┆ ensation  ┆ Voucher   ┆ Shipping  │
│ ---       ┆ str      ┆ Date      ┆ Date      ┆   ┆ Seller    ┆ ---       ┆ ---       ┆ Fees      │
│ str       ┆          ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ ---       │
│           ┆          ┆ date      ┆ date      ┆   ┆ str       ┆           ┆           ┆ f64       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [103]:
recon.columns

['OrderNum',
 'MarketPlaceOrderNum',
 'WorkDate',
 'SalesCenterAmount',
 'Sales Month',
 'Pymt Date',
 'Pymt Mth',
 'Pymt Amt',
 'Commission Fee',
 'Transaction Fee',
 'Service Fee',
 'AMS Commission Fee',
 'Return QC Fee',
 'Voucher/(Disc rebate)',
 'Refund',
 'Actual Shipping Fee',
 'Outstanding',
 'Remarks',
 'Order Status',
 'Shipping fee paid by Shopee',
 'Lost Compensation',
 'Rebate Provided by Shopee',
 'Checking',
 'Refund Adj Mth 1',
 'Refund Adj 1',
 'Refund Adj Mth 2',
 'Refund Adj 2',
 'Shrinkage Adj Mth',
 'Shrinkage Adj',
 'Deduction of Affiliate Marketing Solution commission fee Adj Mth',
 'Deduction of Affiliate Marketing Solution commission fee Adj Mth 1',
 'Voucher Adj Mth',
 'Voucher Adj',
 'Shipping Fee Adj Mth 1',
 'Shipping Fee Adj 1',
 'Shipping Fee Adj Mth 2',
 'Shipping Fee Adj 2',
 'Oustanding Balance',
 '.',
 'Order ID']

In [95]:
checkreport = balance_all_withdrawal.join(recon, on="Order ID", how="inner")
checkreport.head(100)

shape: (0, 43)
┌────────────┬────────────┬────────────┬──────────┬───┬────────────┬────────────┬────────────┬─────┐
│ Date       ┆ Transactio ┆ Descriptio ┆ Order ID ┆ … ┆ Shipping   ┆ Shipping   ┆ Oustanding ┆ .   │
│ ---        ┆ n Type     ┆ n          ┆ ---      ┆   ┆ Fee Adj    ┆ Fee Adj 2  ┆ Balance    ┆ --- │
│ datetime[μ ┆ ---        ┆ ---        ┆ str      ┆   ┆ Mth 2      ┆ ---        ┆ ---        ┆ str │
│ s]         ┆ str        ┆ str        ┆          ┆   ┆ ---        ┆ str        ┆ f64        ┆     │
│            ┆            ┆            ┆          ┆   ┆ str        ┆            ┆            ┆     │
╞════════════╪════════════╪════════════╪══════════╪═══╪════════════╪════════════╪════════════╪═════╡
└────────────┴────────────┴────────────┴──────────┴───┴────────────┴────────────┴────────────┴─────┘

### Bringing Sales Report

In [15]:
sales_files = sorted(root.parent.glob("SalesReport*.xlsx"))
print("=== Sales Reports ===")
print([f.name for f in sales_files])

sales_dfs = []
for f in sales_files:
    df = pl.read_excel(f, sheet_name="SalesReport", has_header=True)
    df = df.with_columns(pl.lit(f.name).alias("_source_file"))
    sales_dfs.append(df)

sales_report = pl.concat(sales_dfs, how="diagonal_relaxed") if sales_dfs else pl.DataFrame()
print("sales_report shape:", sales_report.shape)

sales_report.head()

=== Sales Reports ===
['SalesReport Wk2.xlsx', 'SalesReport Wk3.xlsx']

Could not determine dtype for column 6, falling back to string
Could not determine dtype for column 8, falling back to string
Could not determine dtype for column 6, falling back to string
Could not determine dtype for column 8, falling back to string

sales_report shape: (62427, 10)

shape: (5, 10)
┌────────────┬────────────┬────────────┬───────────┬───┬───────┬───────────┬───────────┬───────────┐
│ OrderNum   ┆ MarketPlac ┆ SalesGloba ┆ eStoreCod ┆ … ┆ PayId ┆ TenderTyp ┆ TlogCount ┆ _source_f │
│ ---        ┆ eOrderNum  ┆ lTxnID     ┆ e         ┆   ┆ ---   ┆ e         ┆ ---       ┆ ile       │
│ str        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ str   ┆ ---       ┆ str       ┆ ---       │
│            ┆ str        ┆ i64        ┆ i64       ┆   ┆       ┆ str       ┆           ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════╪═══════════╪═══════════╪═══════════╡
│ 9524949786 ┆ 2601044PUM ┆ 233603239  ┆ 895       ┆ … ┆ null  ┆ eMarket   ┆ null      ┆ SalesRepo │
│            ┆ 2781       ┆            ┆           ┆   ┆       ┆ Place     ┆           ┆ rt        │
│            ┆            ┆            ┆           ┆   ┆       ┆           ┆           ┆ Wk2.xlsx  │
│ 9524950020 ┆ 26010450MF ┆ 233603241  ┆ 895       ┆ … ┆ null  ┆ eMarket   ┆ null      ┆ SalesRepo │
│            ┆ PQE1       ┆            ┆           ┆   ┆       ┆ Place     ┆           ┆ rt        │
│            ┆            ┆            ┆           ┆   ┆       ┆           ┆           ┆ Wk2.xlsx  │
│ 9524951072 ┆ 2601045R7N ┆ 233603245  ┆ 895       ┆ … ┆ null  ┆ eMarket   ┆ null      ┆ SalesRepo │
│            ┆ TP28       ┆            ┆           ┆   ┆       ┆ Place     ┆           ┆ rt        │
│            ┆            ┆            ┆           ┆   ┆       ┆           ┆           ┆ Wk2.xlsx  │
│ 9524928466 ┆ 260101TUY6 ┆ 233603250  ┆ 895       ┆ … ┆ null  ┆ eMarket   ┆ null      ┆ SalesRepo │
│            ┆ HNTV       ┆            ┆           ┆   ┆       ┆ Place     ┆           ┆ rt        │
│            ┆            ┆            ┆           ┆   ┆       ┆           ┆           ┆ Wk2.xlsx  │
│ 9524930857 ┆ 260101UF58 ┆ 233603253  ┆ 895       ┆ … ┆ null  ┆ eMarket   ┆ null      ┆ SalesRepo │
│            ┆ WU38       ┆            ┆           ┆   ┆       ┆ Place     ┆           ┆ rt        │
│            ┆            ┆            ┆           ┆   ┆       ┆           ┆           ┆ Wk2.xlsx  │
└────────────┴────────────┴────────────┴───────────┴───┴───────┴───────────┴───────────┴───────────┘

In [16]:
sales_report.columns

['OrderNum',
 'MarketPlaceOrderNum',
 'SalesGlobalTxnID',
 'eStoreCode',
 'SalesWorkDate',
 'TotalAmount',
 'PayId',
 'TenderType',
 'TlogCount',
 '_source_file']

In [79]:
# Normalize sales report
sales_report_normalized = (
    sales_report
    .with_columns([
        # `SalesWorkDate` may already be a Date/Datetime (from Excel reader),
        # or it may be a string like "31-12-2025"; handle both safely.
        pl.coalesce([
            pl.col("SalesWorkDate").cast(pl.Date, strict=False),
            pl.col("SalesWorkDate")
              .cast(pl.Utf8, strict=False)
              .str.strip_chars()
              .str.strptime(pl.Date, "%d-%m-%Y", strict=False),
        ]).alias("SalesWorkDate"),
        pl.col("MarketPlaceOrderNum").cast(pl.Utf8).str.strip_chars().alias("Order ID"),
    ])
)
sales_report_normalized.head()

shape: (5, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ OrderNum  ┆ MarketPla ┆ SalesGlob ┆ eStoreCod ┆ … ┆ TenderTyp ┆ TlogCount ┆ _source_f ┆ Order ID │
│ ---       ┆ ceOrderNu ┆ alTxnID   ┆ e         ┆   ┆ e         ┆ ---       ┆ ile       ┆ ---      │
│ str       ┆ m         ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ ---       ┆ str      │
│           ┆ ---       ┆ i64       ┆ i64       ┆   ┆ str       ┆           ┆ str       ┆          │
│           ┆ str       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 952494978 ┆ 2601044PU ┆ 233603239 ┆ 895       ┆ … ┆ eMarket   ┆ null      ┆ SalesRepo ┆ 2601044P │
│ 6         ┆ M2781     ┆           ┆           ┆   ┆ Place     ┆           ┆ rt        ┆ UM2781   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Wk2.xlsx  ┆          │
│ 952495002 ┆ 26010450M ┆ 233603241 ┆ 895       ┆ … ┆ eMarket   ┆ null      ┆ SalesRepo ┆ 26010450 │
│ 0         ┆ FPQE1     ┆           ┆           ┆   ┆ Place     ┆           ┆ rt        ┆ MFPQE1   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Wk2.xlsx  ┆          │
│ 952495107 ┆ 2601045R7 ┆ 233603245 ┆ 895       ┆ … ┆ eMarket   ┆ null      ┆ SalesRepo ┆ 2601045R │
│ 2         ┆ NTP28     ┆           ┆           ┆   ┆ Place     ┆           ┆ rt        ┆ 7NTP28   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Wk2.xlsx  ┆          │
│ 952492846 ┆ 260101TUY ┆ 233603250 ┆ 895       ┆ … ┆ eMarket   ┆ null      ┆ SalesRepo ┆ 260101TU │
│ 6         ┆ 6HNTV     ┆           ┆           ┆   ┆ Place     ┆           ┆ rt        ┆ Y6HNTV   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Wk2.xlsx  ┆          │
│ 952493085 ┆ 260101UF5 ┆ 233603253 ┆ 895       ┆ … ┆ eMarket   ┆ null      ┆ SalesRepo ┆ 260101UF │
│ 7         ┆ 8WU38     ┆           ┆           ┆   ┆ Place     ┆           ┆ rt        ┆ 58WU38   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Wk2.xlsx  ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [80]:
sales_report_report = sales_report_normalized.select(pl.col("Order ID", "SalesWorkDate"))
sales_report_report.head()

shape: (5, 2)
┌────────────────┬───────────────┐
│ Order ID       ┆ SalesWorkDate │
│ ---            ┆ ---           │
│ str            ┆ date          │
╞════════════════╪═══════════════╡
│ 2601044PUM2781 ┆ 2026-01-05    │
│ 26010450MFPQE1 ┆ 2026-01-05    │
│ 2601045R7NTP28 ┆ 2026-01-05    │
│ 260101TUY6HNTV ┆ 2026-01-05    │
│ 260101UF58WU38 ┆ 2026-01-05    │
└────────────────┴───────────────┘

In [96]:
# Get Order IDs from each dataframe
recon_ids = recon.select("Order ID")
sales_ids = sales_report_normalized.select("Order ID")
balance_ids = balance_all_normalized.select("Order ID")

# Find common Order IDs across all three
common_ids = (
    recon_ids
    .join(sales_ids, on="Order ID", how="inner")
    .join(balance_ids, on="Order ID", how="inner")
    .unique("Order ID")
)

print(f"Order IDs in all three sources: {common_ids.height}")
common_ids.head(20)

Order IDs in all three sources: 7862

shape: (20, 1)
┌────────────────┐
│ Order ID       │
│ ---            │
│ str            │
╞════════════════╡
│ 2601046NSCRFCU │
│ 26010349F27NWJ │
│ 2601045TNC0XS3 │
│ 2601069PFCA9QB │
│ 2601020REFUY1G │
│ …              │
│ 2601045BG68B71 │
│ 2601058A3N83H2 │
│ 2601033R48K1XC │
│ 251231SSWH9YPD │
│ 2601021P6VEMX6 │
└────────────────┘

In [97]:
balance_all.filter(pl.col("Order ID") == "2601069PFCA9QB").head()

shape: (1, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Date      ┆ Transacti ┆ Descripti ┆ Order ID  ┆ … ┆ my_balanc ┆ my_balanc ┆ my_balanc ┆ my_balan │
│ ---       ┆ on Type   ┆ on        ┆ ---       ┆   ┆ e_transac ┆ e_transac ┆ e_transac ┆ ce_trans │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ tion_repo ┆ tion_repo ┆ tion_repo ┆ action_r │
│           ┆ str       ┆ str       ┆           ┆   ┆ rt.…      ┆ rt.…      ┆ rt.…      ┆ eport.…  │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2026-01-0 ┆ Order     ┆ Income    ┆ 2601069PF ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 7         ┆ Income    ┆ from      ┆ CA9QB     ┆   ┆           ┆           ┆           ┆          │
│ 18:21:16  ┆           ┆ Order #26 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 01069PFCA ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ …         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [98]:
recon.filter(pl.col("Order ID") == "2601069PFCA9QB").head()

shape: (1, 40)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬──────┬───────────┐
│ OrderNum   ┆ MarketPlac ┆ WorkDate   ┆ SalesCente ┆ … ┆ Shipping  ┆ Oustandin ┆ .    ┆ Order ID  │
│ ---        ┆ eOrderNum  ┆ ---        ┆ rAmount    ┆   ┆ Fee Adj 2 ┆ g Balance ┆ ---  ┆ ---       │
│ str        ┆ ---        ┆ str        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ str  ┆ str       │
│            ┆ str        ┆            ┆ f64        ┆   ┆ str       ┆ f64       ┆      ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════╪═══════════╡
│ 9524962601 ┆ 2601069PFC ┆ 2026-01-07 ┆ 19.6       ┆ … ┆ null      ┆ 6.6613e-1 ┆ null ┆ 2601069PF │
│            ┆ A9QB       ┆ 00:00:00   ┆            ┆   ┆           ┆ 6         ┆      ┆ CA9QB     │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴──────┴───────────┘

In [100]:
sales_report_normalized.filter(pl.col("Order ID") == "2601069PFCA9QB").head()

shape: (1, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ OrderNum  ┆ MarketPla ┆ SalesGlob ┆ eStoreCod ┆ … ┆ TenderTyp ┆ TlogCount ┆ _source_f ┆ Order ID │
│ ---       ┆ ceOrderNu ┆ alTxnID   ┆ e         ┆   ┆ e         ┆ ---       ┆ ile       ┆ ---      │
│ str       ┆ m         ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ ---       ┆ str      │
│           ┆ ---       ┆ i64       ┆ i64       ┆   ┆ str       ┆           ┆ str       ┆          │
│           ┆ str       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 952496260 ┆ 2601069PF ┆ 234084936 ┆ 895       ┆ … ┆ eMarket   ┆ null      ┆ SalesRepo ┆ 2601069P │
│ 1         ┆ CA9QB     ┆           ┆           ┆   ┆ Place     ┆           ┆ rt        ┆ FCA9QB   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Wk2.xlsx  ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [101]:
income_all_normalized.filter(pl.col("Order ID") == "2601069PFCA9QB").head()

shape: (1, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Sequence  ┆ Order ID  ┆ Order     ┆ Payout    ┆ … ┆ Voucher   ┆ Lost Comp ┆ Net       ┆ Net      │
│ No.       ┆ ---       ┆ Creation  ┆ Completed ┆   ┆ Code From ┆ ensation  ┆ Voucher   ┆ Shipping │
│ ---       ┆ str       ┆ Date      ┆ Date      ┆   ┆ Seller    ┆ ---       ┆ ---       ┆ Fees     │
│ str       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆ date      ┆ date      ┆   ┆ str       ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 641       ┆ 2601069PF ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆           ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆ CA9QB     ┆ 6         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [102]:
income_all_normalized.select(pl.col("Transaction Fee (Incl. SST)")).head()

shape: (5, 1)
┌─────────────────────────────┐
│ Transaction Fee (Incl. SST) │
│ ---                         │
│ f64                         │
╞═════════════════════════════╡
│ 0.0                         │
│ 0.0                         │
│ -2.14                       │
│ -1.99                       │
│ -1.39                       │
└─────────────────────────────┘

### Generate Report

In [28]:
income_all_normalized.columns

['Sequence No.',
 'Order ID',
 'Order Creation Date',
 'Payout Completed Date',
 'Total Released Amount (RM)',
 'Product Price',
 'Refund Amount',
 'Shipping Fee Paid by Buyer (excl. SST)',
 'Shipping Fee Charged by Logistic Provider',
 'Seller Paid Shipping Fee SST',
 'Shipping Rebate From Shopee',
 'Reverse Shipping Fee',
 'Reverse Shipping Fee SST',
 'Saver Programme Shipping Fee Savings',
 'Return to Seller Fee',
 'Rebate Provided by Shopee',
 'Voucher Sponsored by Seller',
 'Coin Cashback Sponsored by Seller',
 'Commission Fee (incl. SST)',
 'Service Fee (Incl. SST)',
 'Transaction Fee (Incl. SST)',
 'AMS Commission Fee',
 'Saver Programme Fee (Incl. SST)',
 'Username (Buyer)',
 'Transaction Fee Rate (%)',
 'Buyer Payment Method',
 'Buyer Payment Method Details_1(if applicable)',
 'Payment Details / Installment Plan',
 'Voucher Code From Seller',
 'Lost Compensation']

In [29]:
# Add "Net Voucher" column as sum of all voucher-related columns (treating nulls as 0)
income_all_normalized = income_all_normalized.with_columns(
    pl.sum_horizontal([
        pl.col('Rebate Provided by Shopee'),
        pl.col('Voucher Sponsored by Seller'),
        pl.col('Coin Cashback Sponsored by Seller')
    ]).fill_null(0).alias("Net Voucher")
)

In [30]:
income_all_normalized = income_all_normalized.with_columns(
    pl.sum_horizontal([
        pl.col('Shipping Fee Paid by Buyer (excl. SST)'),
        pl.col('Shipping Fee Charged by Logistic Provider'),
        pl.col('Seller Paid Shipping Fee SST'),
        pl.col('Shipping Rebate From Shopee'),
        pl.col('Reverse Shipping Fee'),
        pl.col('Reverse Shipping Fee SST')
    ]).fill_null(0).alias("Net Shipping Fees")
)
income_all_normalized.head()

shape: (5, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Sequence  ┆ Order ID  ┆ Order     ┆ Payout    ┆ … ┆ Voucher   ┆ Lost Comp ┆ Net       ┆ Net      │
│ No.       ┆ ---       ┆ Creation  ┆ Completed ┆   ┆ Code From ┆ ensation  ┆ Voucher   ┆ Shipping │
│ ---       ┆ str       ┆ Date      ┆ Date      ┆   ┆ Seller    ┆ ---       ┆ ---       ┆ Fees     │
│ str       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆ date      ┆ date      ┆   ┆ str       ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 251230QHF ┆ 2025-12-3 ┆ 2025-12-3 ┆ … ┆           ┆ 0.0       ┆ 0.0       ┆ -5.19    │
│           ┆ 7YGBE     ┆ 0         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 251230PMP ┆ 2025-12-3 ┆ 2025-12-3 ┆ … ┆           ┆ 0.0       ┆ 0.0       ┆ -2.65    │
│           ┆ 6MTW6     ┆ 0         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 251230PB5 ┆ 2025-12-3 ┆ 2025-12-3 ┆ … ┆           ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆ YG8HT     ┆ 0         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 7         ┆ 251230PB3 ┆ 2025-12-3 ┆ 2025-12-3 ┆ … ┆           ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆ GD63E     ┆ 0         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 10        ┆ 251230PAY ┆ 2025-12-3 ┆ 2025-12-3 ┆ … ┆           ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆ 9XQWY     ┆ 0         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [31]:
balance_all_report = balance_all_normalized.select([
    'Date', 'Order ID'])
#Change the Date time to Date only for easier matching with income report (which only has date, no time)
balance_all_report = balance_all_report.with_columns(
    pl.col("Date").dt.date().alias("Payment Date")
)
balance_all_report = balance_all_report.with_columns(
    pl.col("Payment Date").dt.strftime("%d-%b-%Y").str.to_uppercase().alias("Payment Date")
)
balance_all_report = balance_all_report.with_columns(
    pl.col("Order ID").str.strip_chars(),
    pl.col("Payment Date")
)
balance_all_report.head()

shape: (5, 3)
┌─────────────────────┬────────────────┬──────────────┐
│ Date                ┆ Order ID       ┆ Payment Date │
│ ---                 ┆ ---            ┆ ---          │
│ datetime[μs]        ┆ str            ┆ str          │
╞═════════════════════╪════════════════╪══════════════╡
│ 2026-01-07 23:59:53 ┆ 251227FMQA3XGP ┆ 07-JAN-2026  │
│ 2026-01-07 23:59:46 ┆ 260102VN9VMVPV ┆ 07-JAN-2026  │
│ 2026-01-07 23:59:32 ┆ 2601045P6TK6PG ┆ 07-JAN-2026  │
│ 2026-01-07 23:59:28 ┆ 2601045Y4YTEG6 ┆ 07-JAN-2026  │
│ 2026-01-07 23:59:26 ┆ 2601045E6UGTNU ┆ 07-JAN-2026  │
└─────────────────────┴────────────────┴──────────────┘

In [81]:
report = income_all_normalized.join(
    balance_all_report,
    on="Order ID",
    how="inner",
)
report.head(10)

shape: (10, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Sequence  ┆ Order ID  ┆ Order     ┆ Payout    ┆ … ┆ Net       ┆ Net       ┆ Date      ┆ Payment  │
│ No.       ┆ ---       ┆ Creation  ┆ Completed ┆   ┆ Voucher   ┆ Shipping  ┆ ---       ┆ Date     │
│ ---       ┆ str       ┆ Date      ┆ Date      ┆   ┆ ---       ┆ Fees      ┆ datetime[ ┆ ---      │
│ str       ┆           ┆ ---       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ μs]       ┆ str      │
│           ┆           ┆ date      ┆ date      ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1813      ┆ 251227FMQ ┆ 2025-12-2 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-2 │
│           ┆ A3XGP     ┆ 7         ┆ 7         ┆   ┆           ┆           ┆ 7         ┆ 026      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 23:59:53  ┆          │
│ 8862      ┆ 260102VN9 ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-2 │
│           ┆ VMVPV     ┆ 2         ┆ 7         ┆   ┆           ┆           ┆ 7         ┆ 026      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 23:59:46  ┆          │
│ 6896      ┆ 2601045P6 ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-2 │
│           ┆ TK6PG     ┆ 4         ┆ 7         ┆   ┆           ┆           ┆ 7         ┆ 026      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 23:59:32  ┆          │
│ 6428      ┆ 2601045Y4 ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-2 │
│           ┆ YTEG6     ┆ 4         ┆ 7         ┆   ┆           ┆           ┆ 7         ┆ 026      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 23:59:28  ┆          │
│ 7123      ┆ 2601045E6 ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-2 │
│           ┆ UGTNU     ┆ 4         ┆ 7         ┆   ┆           ┆           ┆ 7         ┆ 026      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 23:59:26  ┆          │
│ 4176      ┆ 26010575H ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-2 │
│           ┆ F5Q6D     ┆ 5         ┆ 7         ┆   ┆           ┆           ┆ 7         ┆ 026      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 23:59:06  ┆          │
│ 7612      ┆ 26010347C ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-2 │
│           ┆ 470NX     ┆ 3         ┆ 7         ┆   ┆           ┆           ┆ 7         ┆ 026      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 23:59:02  ┆          │
│ 493       ┆ 260101UAH ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-2 │
│           ┆ S8FRR     ┆ 1         ┆ 7         ┆   ┆           ┆           ┆ 7         ┆ 026      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 23:58:33  ┆          │
│ 557       ┆ 2601069VS ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-2 │
│           ┆ E7UX0     ┆ 6         ┆ 7         ┆   ┆           ┆           ┆ 7         ┆ 026      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 23:58:22  ┆          │
│ 2377      ┆ 2512235NA ┆ 2025-12-2 ┆ 2026-01-0 ┆ … ┆ -9.0      ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-2 │
│           ┆ 29GPW     ┆ 3         ┆ 7         ┆   ┆           ┆           ┆ 7         ┆ 026      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 23:58:05  ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [82]:
report = report.with_columns(
     pl.col("Date").dt.strftime("%b-%Y").str.to_uppercase().alias("Payment Mth")
)
report.head()

shape: (5, 35)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Sequence  ┆ Order ID  ┆ Order     ┆ Payout    ┆ … ┆ Net       ┆ Date      ┆ Payment   ┆ Payment  │
│ No.       ┆ ---       ┆ Creation  ┆ Completed ┆   ┆ Shipping  ┆ ---       ┆ Date      ┆ Mth      │
│ ---       ┆ str       ┆ Date      ┆ Date      ┆   ┆ Fees      ┆ datetime[ ┆ ---       ┆ ---      │
│ str       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ μs]       ┆ str       ┆ str      │
│           ┆           ┆ date      ┆ date      ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1813      ┆ 251227FMQ ┆ 2025-12-2 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-20 ┆ JAN-2026 │
│           ┆ A3XGP     ┆ 7         ┆ 7         ┆   ┆           ┆ 7         ┆ 26        ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 23:59:53  ┆           ┆          │
│ 8862      ┆ 260102VN9 ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-20 ┆ JAN-2026 │
│           ┆ VMVPV     ┆ 2         ┆ 7         ┆   ┆           ┆ 7         ┆ 26        ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 23:59:46  ┆           ┆          │
│ 6896      ┆ 2601045P6 ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-20 ┆ JAN-2026 │
│           ┆ TK6PG     ┆ 4         ┆ 7         ┆   ┆           ┆ 7         ┆ 26        ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 23:59:32  ┆           ┆          │
│ 6428      ┆ 2601045Y4 ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-20 ┆ JAN-2026 │
│           ┆ YTEG6     ┆ 4         ┆ 7         ┆   ┆           ┆ 7         ┆ 26        ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 23:59:28  ┆           ┆          │
│ 7123      ┆ 2601045E6 ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-20 ┆ JAN-2026 │
│           ┆ UGTNU     ┆ 4         ┆ 7         ┆   ┆           ┆ 7         ┆ 26        ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 23:59:26  ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [83]:
report.head()

shape: (5, 35)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Sequence  ┆ Order ID  ┆ Order     ┆ Payout    ┆ … ┆ Net       ┆ Date      ┆ Payment   ┆ Payment  │
│ No.       ┆ ---       ┆ Creation  ┆ Completed ┆   ┆ Shipping  ┆ ---       ┆ Date      ┆ Mth      │
│ ---       ┆ str       ┆ Date      ┆ Date      ┆   ┆ Fees      ┆ datetime[ ┆ ---       ┆ ---      │
│ str       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ μs]       ┆ str       ┆ str      │
│           ┆           ┆ date      ┆ date      ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1813      ┆ 251227FMQ ┆ 2025-12-2 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-20 ┆ JAN-2026 │
│           ┆ A3XGP     ┆ 7         ┆ 7         ┆   ┆           ┆ 7         ┆ 26        ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 23:59:53  ┆           ┆          │
│ 8862      ┆ 260102VN9 ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-20 ┆ JAN-2026 │
│           ┆ VMVPV     ┆ 2         ┆ 7         ┆   ┆           ┆ 7         ┆ 26        ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 23:59:46  ┆           ┆          │
│ 6896      ┆ 2601045P6 ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-20 ┆ JAN-2026 │
│           ┆ TK6PG     ┆ 4         ┆ 7         ┆   ┆           ┆ 7         ┆ 26        ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 23:59:32  ┆           ┆          │
│ 6428      ┆ 2601045Y4 ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-20 ┆ JAN-2026 │
│           ┆ YTEG6     ┆ 4         ┆ 7         ┆   ┆           ┆ 7         ┆ 26        ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 23:59:28  ┆           ┆          │
│ 7123      ┆ 2601045E6 ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 0.0       ┆ 2026-01-0 ┆ 07-JAN-20 ┆ JAN-2026 │
│           ┆ UGTNU     ┆ 4         ┆ 7         ┆   ┆           ┆ 7         ┆ 26        ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 23:59:26  ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [84]:
PaymentDetail= report.join(
    sales_report_report,   
    on="Order ID",
    how="inner"
)
PaymentDetail.head()

shape: (5, 36)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Sequence  ┆ Order ID  ┆ Order     ┆ Payout    ┆ … ┆ Date      ┆ Payment   ┆ Payment   ┆ SalesWor │
│ No.       ┆ ---       ┆ Creation  ┆ Completed ┆   ┆ ---       ┆ Date      ┆ Mth       ┆ kDate    │
│ ---       ┆ str       ┆ Date      ┆ Date      ┆   ┆ datetime[ ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆ ---       ┆ ---       ┆   ┆ μs]       ┆ str       ┆ str       ┆ date     │
│           ┆           ┆ date      ┆ date      ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 118       ┆ 2601045R7 ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 2026-01-0 ┆ 05-JAN-20 ┆ JAN-2026  ┆ 2026-01- │
│           ┆ NTP28     ┆ 4         ┆ 5         ┆   ┆ 5         ┆ 26        ┆           ┆ 05       │
│           ┆           ┆           ┆           ┆   ┆ 14:37:37  ┆           ┆           ┆          │
│ 9263      ┆ 260101UF5 ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 2026-01-0 ┆ 05-JAN-20 ┆ JAN-2026  ┆ 2026-01- │
│           ┆ 8WU38     ┆ 1         ┆ 5         ┆   ┆ 5         ┆ 26        ┆           ┆ 05       │
│           ┆           ┆           ┆           ┆   ┆ 14:52:46  ┆           ┆           ┆          │
│ 8858      ┆ 260102VNE ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 2026-01-0 ┆ 07-JAN-20 ┆ JAN-2026  ┆ 2026-01- │
│           ┆ Q4SRV     ┆ 2         ┆ 7         ┆   ┆ 7         ┆ 26        ┆           ┆ 05       │
│           ┆           ┆           ┆           ┆   ┆ 00:35:23  ┆           ┆           ┆          │
│ 3774      ┆ 2601044RA ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 2026-01-0 ┆ 06-JAN-20 ┆ JAN-2026  ┆ 2026-01- │
│           ┆ BCD24     ┆ 4         ┆ 6         ┆   ┆ 6         ┆ 26        ┆           ┆ 05       │
│           ┆           ┆           ┆           ┆   ┆ 08:21:59  ┆           ┆           ┆          │
│ 5702      ┆ 2601021CA ┆ 2026-01-0 ┆ 2026-01-0 ┆ … ┆ 2026-01-0 ┆ 05-JAN-20 ┆ JAN-2026  ┆ 2026-01- │
│           ┆ UPAJK     ┆ 2         ┆ 5         ┆   ┆ 5         ┆ 26        ┆           ┆ 05       │
│           ┆           ┆           ┆           ┆   ┆ 15:47:42  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [77]:
sales_report_report.head()

shape: (5, 2)
┌────────────┬───────────────┐
│ Order ID   ┆ SalesWorkDate │
│ ---        ┆ ---           │
│ str        ┆ date          │
╞════════════╪═══════════════╡
│ 9524949786 ┆ 2026-01-05    │
│ 9524950020 ┆ 2026-01-05    │
│ 9524951072 ┆ 2026-01-05    │
│ 9524928466 ┆ 2026-01-05    │
│ 9524930857 ┆ 2026-01-05    │
└────────────┴───────────────┘

In [63]:
income_not_balance = income_all_normalized.join(
    balance_all_normalized,
    on="Order ID",
    how="anti"
)
income_not_balance.head()

shape: (5, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Sequence  ┆ Order ID  ┆ Order     ┆ Payout    ┆ … ┆ Voucher   ┆ Lost Comp ┆ Net       ┆ Net      │
│ No.       ┆ ---       ┆ Creation  ┆ Completed ┆   ┆ Code From ┆ ensation  ┆ Voucher   ┆ Shipping │
│ ---       ┆ str       ┆ Date      ┆ Date      ┆   ┆ Seller    ┆ ---       ┆ ---       ┆ Fees     │
│ str       ┆           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆ date      ┆ date      ┆   ┆ str       ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 8832      ┆ 2512222NW ┆ 2025-12-2 ┆ 2025-12-3 ┆ … ┆           ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆ K4XVR     ┆ 2         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 9076      ┆ 25122108A ┆ 2025-12-2 ┆ 2025-12-3 ┆ … ┆           ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆ A8SM7     ┆ 1         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 6067      ┆ 251228GK5 ┆ 2025-12-2 ┆ 2026-01-0 ┆ … ┆           ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆ T85K4     ┆ 8         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 7582      ┆ 251225AV1 ┆ 2025-12-2 ┆ 2026-01-0 ┆ … ┆           ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆ ET5T5     ┆ 5         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ 8842      ┆ 2512221YJ ┆ 2025-12-2 ┆ 2026-01-0 ┆ … ┆           ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆ BXS68     ┆ 2         ┆ 1         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [64]:
balance_not_income = balance_all_normalized.join(
    income_all_normalized, 
    on="Order ID",
    how="anti"
)
balance_not_income.head()

shape: (5, 4)
┌─────────────────────┬──────────────────┬─────────────────────────────────┬────────────────┐
│ Date                ┆ Transaction Type ┆ Description                     ┆ Order ID       │
│ ---                 ┆ ---              ┆ ---                             ┆ ---            │
│ datetime[μs]        ┆ str              ┆ str                             ┆ str            │
╞═════════════════════╪══════════════════╪═════════════════════════════════╪════════════════╡
│ 2026-01-07 18:18:01 ┆ Adjustment       ┆ Lost Compensation for parcel #… ┆ 251227FHQ8CDPK │
│ 2026-01-07 17:18:27 ┆ Adjustment       ┆ Wallet Adjustment due to Buyer… ┆ 251026534124X4 │
│ 2026-01-07 02:32:18 ┆ Withdrawals      ┆ Automated Withdrawal            ┆ -              │
│ 2026-01-07 02:32:18 ┆ Withdrawals      ┆ Automated Withdrawal            ┆ -              │
│ 2026-01-07 02:32:18 ┆ Withdrawals      ┆ Automated Withdrawal            ┆ -              │
└─────────────────────┴──────────────────┴─────────────────────────────────┴────────────────┘

### Export Result Out to Excel File

In [66]:
workbook = xlsxwriter.Workbook("output.xlsx")

# Function to write polars dataframe to worksheet
def write_polars_to_sheet(workbook, sheet_name, df):
    worksheet = workbook.add_worksheet(sheet_name)

    # Write header
    for col_idx, column in enumerate(df.columns):
        worksheet.write(0, col_idx, column)

    # Write data
    for row_idx, row in enumerate(df.iter_rows()):
        for col_idx, value in enumerate(row):
            worksheet.write(row_idx + 1, col_idx, value)

# Write each dataframe
write_polars_to_sheet(workbook, "report", report)
write_polars_to_sheet(workbook, "Income not in Balance", income_not_balance)
write_polars_to_sheet(workbook, "Balance not in Income", balance_not_income)

workbook.close()